name: Build and Release SwiftFormat .deb Package

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "00 09 * * *"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: swift:5.9-jammy

    steps:
      - name: Fetch latest SwiftFormat tag
        id: fetch-latest-tag
        run: |
          apt update -y && apt install jq curl -y
          echo "tag=$(
            curl https://api.github.com/repos/nicklockwood/SwiftFormat/releases/latest | \
              jq -r '.tag_name'
          )" >> $GITHUB_OUTPUT

      - name: Check if release already exists
        id: check-already-exists
        run: |
          apt update -y && apt install curl -y
          TAG=${{ steps.fetch-latest-tag.outputs.tag }}
          RELEASE=$(
            curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG \
              -w "%{http_code}" \
              -o /dev/null
          )
          if [ "$RELEASE" = "200" ]; then
            echo "Release for tag $TAG already exists."
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "Release for tag $TAG does not exist yet."
            echo "result=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout SwiftFormat
        if: ${{ steps.check-already-exists.outputs.result == 'false' }}
        uses: actions/checkout@v4
        with:
          repository: nicklockwood/SwiftFormat
          ref: ${{ steps.fetch-latest-tag.outputs.tag }}

      - name: Build SwiftFormat
        if: ${{ steps.check-already-exists.outputs.result == 'false' }}
        run: swift build -c release --static-swift-stdlib

      - name: Create .deb package
        if: ${{ steps.check-already-exists.outputs.result == 'false' }}
        run: |
          TAG=${{ steps.fetch-latest-tag.outputs.tag }}
          mkdir -p swiftformat/DEBIAN
          mkdir -p swiftformat/usr/local/bin
          cp .build/release/swiftformat swiftformat/usr/local/bin
          echo "Package: swiftformat\nVersion: $TAG\nMaintainer: Mahdi Bahrami <contact@mahdibm.com>\nArchitecture: amd64\nDescription: Nick Lockwood's SwiftFormat: A formatting tool for Swift programming language" > swiftformat/DEBIAN/control
          dpkg-deb --build swiftformat swiftformat-$TAG-linux-amd64.deb

      - name: Create release
        if: ${{ steps.check-already-exists.outputs.result == 'false' }}
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.fetch-latest-tag.outputs.tag }}
          release_name: SwiftFormat Release ${{ steps.fetch-latest-tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload .deb Package to release
        if: ${{ steps.check-already-exists.outputs.result == 'false' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./swiftformat-${{ steps.fetch-latest-tag.outputs.tag }}-linux-amd64.deb
          asset_name: swiftformat-${{ steps.fetch-latest-tag.outputs.tag }}-linux-amd64.deb
          asset_content_type: application/octet-stream
